<template>
  <div class="min-h-screen bg-gray-900 text-gray-100">
    <header class="bg-blue-700 text-white p-4">
      <div class="container mx-auto flex justify-between items-center flex-wrap gap-2">
        <h1 class="text-2xl font-bold">Hiroshima Summit 2025</h1>
        <div class="flex gap-2">
          <button
            @click="showNowOnly = !showNowOnly"
            :class="['px-4 py-2 rounded', showNowOnly ? 'bg-green-600' : 'bg-blue-800 hover:bg-blue-700']"
          >
            Now
          </button>
          <div class="hidden md:flex gap-2">
            <button
              @click="columnsView = 3"
              :class="['px-4 py-2 rounded', columnsView === 3 ? 'bg-blue-600' : 'bg-blue-800 hover:bg-blue-700']"
            >
              3 Columns
            </button>
            <button
              @click="columnsView = 5"
              :class="['px-4 py-2 rounded', columnsView === 5 ? 'bg-blue-600' : 'bg-blue-800 hover:bg-blue-700']"
            >
              5 Columns
            </button>
          </div>
        </div>
      </div>
    </header>

    <main class="container mx-auto px-4 py-8">
      <div :class="['grid gap-6', showNowOnly ? 'grid-cols-1' : (columnsView === 3 ? 'md:grid-cols-3' : 'md:grid-cols-5'), 'grid-cols-1']">
        <div
          v-for="event in displayedEvents"
          :key="event.date"
          class="mb-6"
          :class="{ 'current-day': !showNowOnly && isCurrentOrFirstDay(event.date) }"
        >
          <div class="flex flex-col gap-4">
            <div class="text-center md:text-left">
              <h2 class="text-xl font-bold mb-2">{{ event.date }}</h2>
              <p v-if="event.registrationDeadline" class="text-gray-400 text-xs">Deadline: {{ event.registrationDeadline }}</p>
            </div>

            <div v-for="dailyEvent in event.events" :key="dailyEvent.time" class="mb-4">
              <div class="bg-gray-800 p-4 rounded-lg h-full">
                <div>
                  <p class="text-gray-400 text-sm">{{ dailyEvent.time }}</p>
                  <h3 class="text-base font-semibold mt-2">{{ dailyEvent.title }}</h3>
                  <p class="text-gray-400 text-xs mt-2 whitespace-pre-line">{{ dailyEvent.description }}</p>
                </div>

                <div class="mt-4 space-y-2 ">
                  <a
                    v-for="action in dailyEvent.actions"
                    :key="action.text"
                    :href="action.link"
                    target="_blank"
                    class="block w-full bg-gray-700 hover:bg-gray-600 text-gray-100 py-2 px-4 rounded transition-colors"
                  >
                    {{ action.text }}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <footer class="bg-gray-800 text-center py-6 px-4">
      <div class="max-w-3xl mx-auto space-y-3">
        <p class="text-sm text-gray-400 font-semibold">
          This page is generated by AI and is NOT affiliated with Hiroshima Setouchi Nomad Fest.
        </p>
        <p class="text-xs text-gray-400">
          All content, event information, and imagery are copyright of their respective owners. This is an unofficial informational page.
        </p>
        <p class="text-sm text-gray-400">
          Please check the official sources for up-to-date information:
          <a href="https://digitalnomadshiroshima.com/hsnf2025/" target="_blank" class="text-blue-400 hover:underline">Hiroshima Setouchi Nomad Fest 2025</a>
          and the event's WhatsApp group.
        </p>
        <p class="text-xs text-gray-500 pt-2 border-t border-gray-700">
          Developed with Claude by <a href="https://websqu.ad" target="_blank" class="text-blue-400 hover:underline">websqu.ad</a>
        </p>
      </div>
    </footer>
  </div>
</template>

<script>
import { ref, computed } from 'vue'
import eventsData from './data/events.json'

export default {
  setup() {
    const events = ref(eventsData.events)
    const columnsView = ref(5)
    const showNowOnly = ref(false)

    // Parse event date to compare with current date
    const parseEventDate = (dateString) => {
      // Parse "October 18 (Sat)" format
      const match = dateString.match(/(\w+)\s+(\d+)/)
      if (!match) return null

      const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December']
      const month = monthNames.indexOf(match[1])
      const day = parseInt(match[2])

      // Assuming 2025 based on the event
      return new Date(2025, month, day)
    }

    // Get current or first day to display
    const getCurrentOrFirstDay = () => {
      const today = new Date()
      today.setHours(0, 0, 0, 0)

      // Find if today matches any event date
      const todayEvent = events.value.find(event => {
        const eventDate = parseEventDate(event.date)
        return eventDate && eventDate.getTime() === today.getTime()
      })

      if (todayEvent) return todayEvent

      // If today is before all events, return first event
      const firstEvent = events.value[0]
      const firstEventDate = parseEventDate(firstEvent.date)

      if (firstEventDate && today < firstEventDate) {
        return firstEvent
      }

      // If during the event period, find the next upcoming day
      for (const event of events.value) {
        const eventDate = parseEventDate(event.date)
        if (eventDate && eventDate >= today) {
          return event
        }
      }

      // If all events have passed, return the last event
      return events.value[events.value.length - 1]
    }

    // Computed property for displayed events
    const displayedEvents = computed(() => {
      if (showNowOnly.value) {
        const currentDay = getCurrentOrFirstDay()
        return currentDay ? [currentDay] : []
      }
      return events.value
    })

    // Check if a date is the current or first day
    const isCurrentOrFirstDay = (dateString) => {
      const currentDay = getCurrentOrFirstDay()
      return currentDay && currentDay.date === dateString
    }

    return {
      events,
      columnsView,
      showNowOnly,
      displayedEvents,
      isCurrentOrFirstDay
    }
  }
}
</script>

<style>
.grid.gap-6 > .mb-6.current-day {
  background-color: rgba(55, 65, 81, 0.75);
  border-radius: 0.5rem;
  padding: 0.5rem;
}
.grid.gap-6 > .mb-6 {
  background-color: rgba(55, 65, 81, 0.15);
  border-radius: 0.5rem;
  padding: 0.5rem;
}
</style>